# This is a basic workflow to help you get started with Actions

name: Generate .jar files from source code and manifests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  generate_jars_from_src:
    name: Generate jars from src
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.head_ref }}

    - name: Change file permissions
      run: |
        chmod +x java-compile.sh
        chmod +x java-jar.sh
        chmod +x test.sh
      
    - name: Compile source code
      run: ./java-compile.sh
    
    - name: Generate jars from manifest
      run: ./java-jar.sh
      
    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v4.4.0
      with:
        # Required
        commit_message: Auto-update binaries

        # Optional commit user and author settings
        commit_user_name: Git Auto Commit Bot
        commit_user_email: git-auto-commit-bot@github.com
        commit_author: Git Auto Commit Bot  <git-auto-commit-bot@github.com>
          
        # Optional: Disable dirty check and always try to create a commit and push
        skip_dirty_check: true


